### ISSUE TITLE
Screamer Radio Preview 2018-08-23

### ISSUE THREAD

**Issue by DavidZidar** [ScreamerRadio/Home#1]
# Release notes

Changes since preview release 2018-08-13

**New features:**
* New setting to allow only one running instance
* Output device selection
* Stereo separation filter (can do mono)
* Ctrl + scroll to adjust volume in smaller steps

**Minor tweaks:**
* Add close current tab to menu
* Moved audio filters to menu instead of in options
* Compressor and stereo separation filter should fade in

**Bug fixes:**
* Could crash on certain streams
* Fixed a few bugs in station export/import
* Stations opened via "Open URL" was not always restored on restart

**Other:**
* Performance improvements in UI
* More exception handling in sensitive places
* Massive internal refactorings to make the code more maintainable

**Comment by MaximusPanin** [comment]
Thanks for the best radio program!
