### ISSUE TITLE
Menu in latest screamer radio classic is unaccessible with screenreaders

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [ScreamerRadio/Home#10]
Hellow @DavidZidar. I blind user of pc. I use your program from the end of 2010 year. For me more convenient interface of classic screamer,but in versions 043 and 044 menu become unaccessible with screenreaders. Yes,i know,what you not support classic version anymore,but please,share at least sources of this version with me,because i know c# and some c++ and can compile and fix it via visual studio. Also classic version not support https streams,which was fixed in new version. If you want contact with me privately,you can do it on email k.sasha1994@yandex.ru.

**Comment by DavidZidar** [comment]
I'm sorry that happened but you are about 10 years too late with this request. I have no plans to release the source code, it's very, very old.

**Comment by AlexandrKozlovskiy** [comment]
But may be you can send to me it privately or help me decompile it,to i can fix it myself.

**Comment by DavidZidar** [comment]
Sorry, no. But maybe you can try the new version and let me know if there's anything that can be improved for accessibility. I have spent a lot of time to make keyboard navigation better in the newest version, but I have never had a screen reader so it is hard for me to know what is not working.
