### ISSUE TITLE
dead project?

### ISSUE THREAD

**Issue by mailinglists35** [ScreamerRadio/Home#12]
could you release the code so maybe others could improve and add features?

**Comment by mailinglists35** [comment]
that's awesome news to hear! regarding the database, would you mind having a look at radio-browser.info and eventually get in touch with the person behind it? it's an semi-open database (for public at least; you can add new stations but editing has been disable because author has not found a way to counter vandalism) and a public open API

**Comment by DavidZidar** [comment]
Vandalism is hard to deal with and is one of the reasons I never built an open system where anyone could edit, though I thought about it a lot. I did have a form where people could submit new stream URLs for me to review for a long time, but ultimately most of the links I got were wrong so it just took longer and made things more difficult.

**Comment by DavidZidar** [comment]
I'm closing this issue now that I have released the new versions, radio-browser.info is requested in a previous issue #4.
