### ISSUE TITLE
Stations completely lost, modern interface unusable. How to roll back, restore all data, and completely disable 'updates?'

### ISSUE THREAD

**Issue by sunlightspectre** [ScreamerRadio/Home#13]
The most recent update is entirely unusable for the visually impaired.  
I'm always wary of people 'updating' things these days, but this was heartbreaking.  
Beyond that, my entire list of stations is gone. None of my backups are registering at all.  
'Sorry, unable to support. Are you sure you selected a valid file?'

Right now, I would like to do as the issue suggests.

**Comment by sunlightspectre** [comment]
Sorry.  

I know this was venting. Rebuilt it, going to try to hand-re-enter hundreds of station entries from an old .json that should be machine readable.

I just hate this. I hate new modernism. I hate searing white voids that my gummed up eyes can't handle, I hate that even other old tech people in my orbit seem to like it. I miss small, human-readable, information-dense user interfaces.    
Doesn't matter. You must like music too, to keep working on this.   
But it's just, every day sees something I depend on ripped away from me.

I appreciated Screamer a lot. Thanks for making it.

**Comment by DavidZidar** [comment]
Can you expand on how it's unusable for the visually impaired?

I tried really hard to make sure nothing would be lost when upgrading but users machines are a really unpredictable environments and it's impossible to test for everything.

Can you list the files in your settings directory? When the new version upgrades the data it first saves `MyStation.json` as `MyStations.json.preserved` and the favorites as `UserSettingsFavorites.json.preserved` as a first measure to protect against loss. Then after the import is done it renames them to `MyStations.json.imported` and `UserSettingsFavorites.json.imported` respectively.

**Comment by sunlightspectre** [comment]
@DavidZidar So, I thought long and hard about whether or not I should write this.   
Understand I'm old. Not 'thirty, boohoo' - old.  
I mean this; there's no future in appealing to people like me.

That said...

_Here are the problems that make it very difficult_ **_for me_** _to use._

[Enclosed is a reference.](https://i.postimg.cc/rq96HPcR/g8a3u9a8uf3auf9au3ef.png)

1. Though there is much more 'room' the theme for modern Screamer has very low contrast.  
You'll notice that the earlier Screamer creates a secondary dark palette as well as the text.  
This helps catch the eye, and create contrast.   
Despite black text standing out on grey, I have trouble distinguishing where one option starts and another ends.  
It can be a real pain, to say the least, and a lot of modern applications do this. 

2. Without reason, the searchbar is smooshed into the options menu.  
If the user - like me - has trouble distinguishing where the former starts and the latter ends, the similar problems arise.  
Further, see how the green of the user's window + distance + contrast make it clear where the search bar _is._   
See also 4.

3. Personal preference, but much more room is used to deliver much less information, much less concisely.  
Elements are scattered throughout, too, with unhelpful pop-up 'guesstimation blurbs.'  
Just as I hate iterative gen misguessing what I'm doing and taking eighty clicks to shut up, I hate having programs trying to guess how user tags relate, throw it on the side of a program like spaghetti, and discouple it from the search results.   
See also 4.

4. Rather than using one window to filter through results, there are now... Two windows.  
This creates more clicks, creating more time spent. This is fine for people who might use a station or two and stop.  
But as someone cycling through stations, this can add up to a surprising amount of time spent.

5. Personal preference, but - this takes up a large amount of visible, usable space.  
For what purpose? There's another stop button, and rarely am I going to edit stations.  
It's an area where the extra context-click is unlikely, and the price of removing it means more dead screen.

Mostly a problem _for me,_ however, is the contrast.  
Even just a more contrasted, system-colours-using client that uses the above as dividers would help visibility _tremendously._  
And that could let you leave a dark client for paying customers, because I do hope you are successful monetising this, because you have put the hard work in.

I have no idea what the internal error is!  
Nothing is working wrong with the client. It might have something to do with the updater. Not sure?

What else...

I back things up paranoically, as do most of my increasingly dying-off circle.   
I was able to get an older version of the client running, as you can see.   
Figuring that I might be able to enter year 2099 as the last time I checked for an update, I tried that to remove the update nag.   
Unfortunately (well, fortunately, perhaps) that's not going to work here, for me.

Suggestions:  

If you're set on adopting any of this, I think the lowest-extra-work solution would be a high-contrast theme.  
You wouldn't have to add extra space to the modern UI, and since the dark UI might have similar issues for _me,_ this could help other users who are struggling. We can't control our eyes. Alas.

Spacing, windows, clicks, etc are all luxuries.     
_I_ would like them, but other users will appreciate the convenient and familiar layout.

And I know the struggle of finding a layout that works for you, that works well for end-users, and then someone comes in and gripes.

Let's see, anything else...  
I was able to retrieve the data, not from the preserved file, but from the stations as is.  
For whatever reason, the preserved file was set as unreadable, and even taking control/adding permissions to access it didn't work. No idea how it got damaged, tried in editra, atom, and wordpad. W10 Pro 64-bit.

I was just really sad. Nothing on your end, and I regret typing without thinking.  
There's a lot I miss. Has nothing to do with you, and I can't emphasise that enough.
