### ISSUE TITLE
Windows hotkeys support

### ISSUE THREAD

**Issue by seerek** [ScreamerRadio/Home#3]
Any chance for windows hotkeys support so that keyboards with "play/pause" and "stop" buttons will pause or resume streaming ?

**Comment by DavidZidar** [comment]
I don't know, I tried to get it to work but it does not seem possible. Windows seems to refuse to create hotkeys for the media keys.

**Comment by seerek** [comment]
Well

Seems that I was misunderstood.
I'm not asking you to define/register special hotkeys for screamer radio .
I want screamer radio to listen to standard windows hotkeys so that if I will have keyboard with media keys, it will allow me to play/pause/stop streaming.

I've tested example code from [StackOverflow](https://stackoverflow.com/a/34290332/22569) and it works perfectly with my [Thinkpad W510 keyboard](http://4.bp.blogspot.com/_NfcpbQRa2YU/TCFtMRnD-oI/AAAAAAAABXA/S_25sgfW-R4/s1600/Lenovo-ThinkPad-W510-keyboard.jpg).
Here is what it printed when I've clicked media keys located on arrows (even when my sample app was not in focus):

> The Key: MediaPlayPause
> The Key: MediaStop
> The Key: MediaNextTrack
> The Key: MediaPreviousTrack

**Comment by DavidZidar** [comment]
I see, you want Screamer to handle the media keys when the window is in focus, yeah that is doable like the example you linked. I'll have a try this weekend.

A hotkey is a system wide keyboard hook, so that's different, from [Wikipedia](https://en.wikipedia.org/wiki/Keyboard_shortcut):
>  a "hotkey" on Windows is a system wide shortcut that is always available in all contexts as long as the program responsible for it is running and not suspended

**Comment by seerek** [comment]
Actually I've mentioned that it works even when app is not in focus because I want this behaviour as a feature.
My scenario is following:

- I want to start screamer radio and run some station
- Then minimize it to try icon
- Then be able to quickly pause/resume/stop radio without clicking every time on try icon - using media keys on my keyboard

Therefore I want it to work even when app is not in focus (minimized).
So I want standard hotkey functionality.

**Comment by DavidZidar** [comment]
I've just released a new [major update](https://www.screamer-radio.com/news/2024-04/welcome-to-the-new-screamer-radio) with a brand new UI and hotkey support is included.

I had to write my own hot key library which I [open sourced](https://github.com/steamcore/TinyHotKey).
