### ISSUE TITLE
New streaming standarts

### ISSUE THREAD

**Issue by filchef** [ScreamerRadio/Home#9]
I can't use new streaming standards
 RTMP - rtmp://lb.blb.cdn.bg:2032/fls/Horizont.stream
HLS - http://lb.blb.cdn.bg:2032/fls/Horizont.stream/playlist.m3u8
RTSP - rtsp://lb.blb.cdn.bg:2032/fls/Horizont.stream
And AAC standard connect very slowly about 1-2 min - http://stream.bnr.bg:8011/horizont.aac

This four standards are used from Bulgarian national radio station  Horizont and all another them stations.
https://bnr.bg/play/?live_stations=1

**Comment by DavidZidar** [comment]
AAC stations should connect a lot faster in the latest version that I recently released. The other standards are not supported by BASS so I can't really do anything quick and easy to solve that.

**Comment by DavidZidar** [comment]
Hi, I've just released a new [major update](https://www.screamer-radio.com/news/2024-04/welcome-to-the-new-screamer-radio) with a brand new UI that also has support for HLS streams and more.

**Comment by Zentie13** [comment]
Is the forum still open for ScreamerRadio? Nothing seems to be happening and no questions answered or replied to.

**Comment by AllanHigdon** [comment]
I've been wondering about that myself.
There's been nothing on GitHub or https://www.screamer-radio.com/ since the last update almost 2 years ago.

**Comment by Zentie13** [comment]
That is such a pity. Probably David passed away or got hijacked. It would be nice if someone else could take over, though.

**Comment by DavidZidar** [comment]
Hi, I'm still around but unfortunately things changed in my life and I had to get a new job and fully focus on that so I haven't really had any time to spend on Screamer Radio the past year except to keep things running. This has always been a side project I'm working on in my spare time, it doesn't even break even unfortunately, even with the new subscription I'm selling, so I can't quit my day job.

**Comment by Zentie13** [comment]
Hi David, good to know you're still around. Life plays nasty trick on us.

As a matter of interest, what whas your subscription, as a matter of interest? I know what you're talking about as I am retired and had to downscale by 70%!

Please let me know how to get our radio station on your list of available stations. I will really appreciate that. Hopefully I can get some subscriptions from Substack and the staion, but I'm not holding my breath...
